name: mspEN

channels:
  - pytorch
  - nvidia
  - defaults

dependencies:
  - python=3.10
  - pip
  - pip:
      - -e .[dev]

  # Windows: CPU-only build
  - pytorch             # [win]
  - torchvision         # [win]
  - cpuonly             # [win]