name: mspEN

channels:
  - pytorch
  - nvidia
  - defaults

dependencies:
  - python=3.10
  - pip
  - pip:
      - -e .

  # Linux: CUDA 12.6 build
  - pytorch             # [linux]
  - torchvision         # [linux]
  - pytorch-cuda=12.6   # [linux]